/**
 * Tag that will be searched for to manage a file with vendorism.
 */
export const tag: "🔒 AUTOGENERATED BY VENDORISM";
/**
 * Additional description to be optionally included with the tag.
 */
export const description: "Removing this comment will prevent it from being managed by it.";
export namespace banners {
    const _default: string;
    export { _default as default };
    export const html: string;
    export const jinja2: string;
    export const handlebars: string;
    export const frontmatter: string;
}
export function transform(content: string, path: string): string;
